// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4rmZEgzkYTplJpMr2mA3n4VkuGiB_7I8',
    appId: '1:731737825079:web:f30c7f1fea988adf8a84b2',
    messagingSenderId: '731737825079',
    projectId: 'minerva-610af',
    authDomain: 'minerva-610af.firebaseapp.com',
    storageBucket: 'minerva-610af.appspot.com',
    measurementId: 'G-GGS6600Z6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSr2NvoEq_iiIVq9JBAJJtThQ6bpnjpgo',
    appId: '1:731737825079:android:994ded08eac5ede48a84b2',
    messagingSenderId: '731737825079',
    projectId: 'minerva-610af',
    storageBucket: 'minerva-610af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_2rah3J_ws6PwWB8-GxXvGDUz-17kUk',
    appId: '1:731737825079:ios:a6326411222e05498a84b2',
    messagingSenderId: '731737825079',
    projectId: 'minerva-610af',
    storageBucket: 'minerva-610af.appspot.com',
    androidClientId: '731737825079-vtjckac8415gd8nkc5nitlsuae9tnidh.apps.googleusercontent.com',
    iosClientId: '731737825079-9hkjd7unsbrms6f9ui3nes6tqfsatge0.apps.googleusercontent.com',
    iosBundleId: 'com.example.minerva',
  );
}
